services:
    app:
        build: .
        container_name: azuriom_app
        working_dir: /var/www/azuriom
        volumes:
            - .:/var/www/azuriom
        networks:
            - azuriom
        environment:
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        # depends_on:
        #     - db

    nginx:
        image: nginx:latest
        container_name: azuriom_nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www/azuriom
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - azuriom
        depends_on:
            - app

    # db:
    #     image: postgres:latest
    #     container_name: azuriom_db
    #     environment:
    #         POSTGRES_DB: azuriom
    #         POSTGRES_USER: azuriom
    #         POSTGRES_PASSWORD: password
    #     volumes:
    #         - db_data:/var/lib/postgresql/data
    #     networks:
    #         - azuriom

networks:
    azuriom:


# volumes:
#     db_data:
